### ISSUE TITLE
Buf.yaml: Multiple modules to have the same path causes extension to stop working

### ISSUE THREAD

**Issue by KinNeko-De** [bufbuild/vscode-buf#347]
Hey..
I am currently writing an article about the integration of buf in visual studio code.
I tried to managed a [gitrepository which contains the apis for multiple applications](https://github.com/KinNeko-De/poc-sample-apicontract-oneapi/tree/feature/define).

I finally found a version where buf lint --config buf.yaml does not report errors because of a wrong package name.
I found the solution with the documentaion: https://buf.build/docs/configuration/v2/buf-yaml/ and the following lines:
Just as side context: The documentation is not correct: https://github.com/bufbuild/buf/issues/3501#issue-2709423066

``` yaml
# Multiple modules are allowed to have the same path, as long as they don't share '.proto' files.
  - path: proto/common
    name: buf.build/acme/weather
    includes:
      - proto/common/weather
  - path: proto/common
    name: buf.build/acme/location
    includes:
      - proto/common/location`
 ```

This is a relativ new feature from [version v1.39.0 of buf.build](https://github.com/bufbuild/buf/blob/bbefdb843ea0ad68f1ab72003dbf40683cf304c1/CHANGELOG.md?plain=1#L87) 

Visual Studio Code:
Version: 1.95.3 (user setup)
Commit: f1a4fb101478ce6ec82fe9627c43efbf9e98c813
Date: 2024-11-13T14:50:04.152Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.22631

Buf version : 1.47.2
Buf vs extension: v0.6.2

The visual code extension stop working with my buf.yaml configuration.

If I start Visual Studio Code no error in proto files are highlighted.
If I remove the lines and save the proto again the error are highlighted.
If I then added the lines my error in protobuf still appear and do not change even if i fix them
![bufExntesion](https://github.com/user-attachments/assets/ff626b0b-0677-4387-be39-e3151e276f9f)

I have no error in the log of Extension Host but I have an error in the developer tools of visual studio code. It happens every time I add the lines and save the proto.
I will attach the log snippet: 
[vscode-app-1733163057834.log](https://github.com/user-attachments/files/17982259/vscode-app-1733163057834.log)

If you need further information let me know please.
