### ISSUE TITLE
Bug - Cannot find .proto file

### ISSUE THREAD

**Issue by antspy** [bufbuild/vscode-buf#404]
Hi, 

I have the following `buf.yaml` file: 

```
version: v2
modules:
  - path: .
    includes:
       - src 
lint:
  use:
    - STANDARD
 ```

with this config, the Buf extension is really slow (I assume this is related to https://github.com/bufbuild/buf/issues/3847, since the extension uses the cli). 

However, after enough time (5 min+), eventually an error is surfaced in the VSCode output logs: 
`Failure: Module "path: ".", includes: "src"" had no .proto files`

which is true, in the sense that there is no `.proto` file directly underneath `src`. However, I have several proto files in subdirectories (e.g. `src/foo/bar.proto`). 

I am using the latest version of the Buf extension (`0.7.2`)
