### ISSUE TITLE
Import external proto file Visual Studio Code error

### ISSUE THREAD

**Issue by kroksys** [bufbuild/vscode-buf#58]
<img width="589" alt="Screenshot 2022-02-17 at 12 00 44" src="https://user-images.githubusercontent.com/15876796/154452582-b27edfaa-89c8-4f21-a07d-21d599666fda.png">

How can I remove this error?
One way would be include `.vscode/settings.json > "protoc": "options": --proto_path` but I cant find where buf store them localy.

**Comment by willsoto** [comment]
I am having this issue as well with `google/type/interval.proto`. Here are my files:

```yaml
version: v1
breaking:
  use:
    - FILE
lint:
  use:
    - MINIMAL
  except:
    - ENUM_VALUE_PREFIX
  # Recommended best practice is to use the buf.yaml to configure files/rules that should be ignored.
  # https://buf.build/docs/lint/overview/#allow_comment_ignores
  allow_comment_ignores: false
  rpc_allow_same_request_response: true
  rpc_allow_google_protobuf_empty_requests: true
  rpc_allow_google_protobuf_empty_responses: true
deps:
  - buf.build/googleapis/googleapis:01f6828d2b8868fc9d314f9ac86677d3253fa33b
```

<img width="554" alt="Screenshot 2023-09-22 at 2 50 48 PM" src="https://github.com/bufbuild/vscode-buf/assets/2791730/6ed5585f-cb56-4ceb-a07a-7fc2cf491c9b">
<img width="347" alt="Screenshot 2023-09-22 at 2 51 15 PM" src="https://github.com/bufbuild/vscode-buf/assets/2791730/e1a3ed41-b3d5-45c8-8766-aec0cfaa5667">

Weirdly, `buf build` and `buf lint` seem to be okay with it?
